title: My personal blog - Chetan Chauhan
email: chauhanchetan82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Chetan Chauhan # add your name
author-pic: chetan-face.jpg
about-author: My name is Chetan Chauhan. I’m a full-time software engineer and web developer who’s been exploring the software world for over 2 years.

# Contact links
email: chauhanchetan82@gmail.com
phone: 8334053394# Add your Phone number
website: foolchetan.github.io # Add your website, do not add http://
linkedin: https://www.linkedin.com/in/chetancchauhan/ # Add your Linkedin handle
github: foolchetan # Add your Github handle
twitter: '@Chauhanchetan82' # Add your Twitter handle
facebook: https://www.facebook.com/chauhanchetan9 # Add your Facebook handle
instagram: https://www.instagram.com/chetanchauhan82/ # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
# markdown: kramdown
markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - 'jekyll-commonmark-ghpages'

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
